# This is a basic workflow to help you get started with Actions

name: Build and Deploy Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        with:
          node-version: 18.12.1
          package-manager: pnpm
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v3.1.1
      #   with:
      #     node-version: 16.17.0

      # - name: Install Dependencies
      #   run: pnpm install

      # - name: Build Documentation
      #   run: pnpm build

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.3.3
      #   with:
      #     branch: gh-pages
      #     folder: docs/.vuepress/dist
      #     token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}
      #     git-config-name: Intersect Bot
      #     git-config-email: bot@ascension.dev
